spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Delivery
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: admin
      password: admin
  jackson:
    serialization:
      fail-on-empty-beans: false
jwt:
  secret: JWTSuperSecretKey
  expirationInMs: 604800000
